apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: random-api

resources:
  - ../../../../apps/random-api/overlays/minimal

commonLabels:
  environment: dev

replicas:
  - name: random-api
    count: 1

images:
  - name: stefanraducan/random-api
    newName: stefanraducan/random-api
    digest: sha256:12aeb663f61305543ae4234e33a19343c2825962b5c7cfb278d5e687ee61b37c

patches:
  - target:
      kind: Deployment
      name: random-api
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "50m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "64Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "100m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "128Mi"
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: http://opentelemetry-collector.opentelemetry.svc.cluster.local:4317
          - name: OTEL_SERVICE_NAME
            value: random-api
