apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - keda-scaledobject.yaml

commonLabels:
  app.kubernetes.io/name: nginx
  app.kubernetes.io/managed-by: argocd
