apiVersion: v1
kind: Service
metadata:
  name: random-api
  namespace: random-api
spec:
  selector:
    app: random-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
