apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: random-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/stefan-raducan/k8s-tests.git
    targetRevision: HEAD
    path: argocd/apps/random-api/base
  destination:
    server: https://kubernetes.default.svc
    namespace: random-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
