apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: random-api

resources:
  - deployment.yaml
  - service.yaml
  - keda-scaledobject.yaml

commonLabels:
  app.kubernetes.io/name: random-api
  app.kubernetes.io/managed-by: argocd
