apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../apps/random-api/base/application.yaml

patches:
  - target:
      kind: Application
      name: random-api
    patch: |-
      - op: replace
        path: /metadata/name
        value: random-api-prod
      - op: replace
        path: /spec/source/targetRevision
        value: main
      - op: replace
        path: /spec/source/path
        value: argocd/apps/random-api/overlays/prod
