name: app-tests

on:
  push:
    branches:
      - main
    paths:
      - "random-api/**"
      - ".github/workflows/app-tests.yml"
  pull_request:
    branches:
      - main
    paths:
      - "random-api/**"
      - ".github/workflows/app-tests.yml"
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: [self-hosted, arc-runner]
    defaults:
      run:
        working-directory: ./random-api

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install httpx pytest

      - name: Run tests
        run: |
          pytest tests/
